name: tincan
description: A Dart library of the Tin Can API

version: 1.0.1
homepage: https://github.com/jblough/TinCanDart
author: Joe Blough <joe.blough@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: any
  http_parser: any
  uuid: any
  crypto: any

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0