name: tincan
description: TincanDart is an xAPI implmentation for the Dart language

version: 2.0.0
homepage: https://github.com/jblough/TinCanDart

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.13.1
  http_parser: ^4.0.0
  uuid: ^3.0.1
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.8
#  build_runner: ^1.0.0
#  build_web_compilers: ^0.4.0
