name: tincan
description: TincanDart in an implmentation of the Tin Can API for the Dart language

version: 1.0.3
homepage: https://github.com/jblough/TinCanDart
author: Joe Blough <joe.blough@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  http_parser: ^3.1.3
  uuid: ^2.0.0
  crypto: ^2.0.6

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0