name: tincan
description: TinCanDart is an xAPI implementation for the Dart programming language

version: 2.1.2
homepage: https://github.com/jblough/TinCanDart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  http_parser: ^4.0.2
  uuid: ^3.0.7
  crypto: ^3.0.2

dev_dependencies:
  test: ^1.24.2
#  build_runner: ^1.0.0
#  build_web_compilers: ^0.4.0
