name: tincan
description: TinCanDart is an xAPI implementation for the Dart programming language

version: 3.0.0
homepage: https://github.com/jblough/TinCanDart

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  http: ^1.0.0
  http_parser: ^4.0.2
  uuid: ^3.0.7
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.3
#  build_runner: ^1.0.0
#  build_web_compilers: ^0.4.0
